# Generated by Django 5.2.7 on 2025-11-04 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='date_created',
            new_name='date_creaeted',
        ),
    ]
