# Generated by Django 5.2.7 on 2025-11-04 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_date_created_movie_date_creaeted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='date_creaeted',
            new_name='date_created',
        ),
    ]
